## 코드

# Import

In [161]:
import pandas as pd
import random
import os
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.multioutput import MultiOutputRegressor
from sklearn.preprocessing import PolynomialFeatures

def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
seed_everything(42) # Seed 고정

# Data Load

In [162]:
train_df = pd.read_csv('train.csv')

train_x = train_df.filter(regex='X') # Input : X Featrue
train_y = train_df.filter(regex='Y') # Output : Y Feature

quadratic = PolynomialFeatures(degree=2) # 차수 = 2
PR = LinearRegression()

# Regression & Inference

## Y1

In [163]:
selected_x = train_df[['X_48', 'X_22', 'X_19', 'X_18', 'X_52', 'X_17', 'X_45', 'X_13', 'X_49', 'X_51', 'X_40', 'X_46', 'X_04', 'X_23', 'X_47', 'X_03', 'X_06', 'X_20', 'X_05', 'X_27', 'X_24', 'X_07', 'X_21', 'X_15', 'X_43', 'X_42', 'X_33', 'X_41', 'X_56', 'X_30', 'X_31', 'X_25', 'X_39']] # selected input : X feature
target_y = train_df['Y_01']
X_quad = quadratic.fit_transform(selected_x.values)

In [164]:
test_x = pd.read_csv('./test.csv')[['X_48', 'X_22', 'X_19', 'X_18', 'X_52', 'X_17', 'X_45', 'X_13', 'X_49', 'X_51', 'X_40', 'X_46', 'X_04', 'X_23', 'X_47', 'X_03', 'X_06', 'X_20', 'X_05', 'X_27', 'X_24', 'X_07', 'X_21', 'X_15', 'X_43', 'X_42', 'X_33', 'X_41', 'X_56', 'X_30', 'X_31', 'X_25', 'X_39']]
PR.fit(X_quad,target_y.values)
arr = PR.predict(quadratic.fit_transform(test_x.values))
preds = []
preds.append(arr)
preds

[array([1.40661554, 1.50023744, 1.35408539, ..., 1.26543326, 1.17566537,
        1.32055691])]

## Y2

In [165]:
selected_x = train_df[['X_48', 'X_22', 'X_18', 'X_43', 'X_17', 'X_51', 'X_42', 'X_49', 'X_40', 'X_05', 'X_52', 'X_06', 'X_45', 'X_27', 'X_24', 'X_25', 'X_56', 'X_09', 'X_19', 'X_20', 'X_46', 'X_04', 'X_23', 'X_47', 'X_16', 'X_15', 'X_41', 'X_28', 'X_39']]
target_y = train_df['Y_02']
X_quad = quadratic.fit_transform(selected_x.values)

In [166]:
test_x = pd.read_csv('./test.csv')[['X_48', 'X_22', 'X_18', 'X_43', 'X_17', 'X_51', 'X_42', 'X_49', 'X_40', 'X_05', 'X_52', 'X_06', 'X_45', 'X_27', 'X_24', 'X_25', 'X_56', 'X_09', 'X_19', 'X_20', 'X_46', 'X_04', 'X_23', 'X_47', 'X_16', 'X_15', 'X_41', 'X_28', 'X_39']]
PR.fit(X_quad,target_y.values)
arr = PR.predict(quadratic.fit_transform(test_x.values))
preds.append(arr)
preds

[array([1.40661554, 1.50023744, 1.35408539, ..., 1.26543326, 1.17566537,
        1.32055691]),
 array([1.17405263, 1.22583945, 1.19551093, ..., 0.96757852, 0.88475016,
        0.98504364])]

## Y3

In [167]:
selected_x = train_df[['X_48', 'X_18', 'X_17', 'X_43', 'X_22', 'X_19', 'X_49', 'X_51', 'X_05', 'X_13', 'X_42', 'X_24', 'X_25', 'X_52', 'X_06', 'X_40', 'X_46', 'X_45', 'X_56', 'X_04', 'X_23', 'X_47', 'X_32', 'X_03', 'X_27', 'X_33', 'X_01', 'X_20', 'X_21', 'X_12', 'X_10', 'X_39', 'X_28', 'X_16', 'X_41']] # selected input : X feature
target_y = train_df['Y_03']
X_quad = quadratic.fit_transform(selected_x.values)

In [168]:
test_x = pd.read_csv('./test.csv')[['X_48', 'X_18', 'X_17', 'X_43', 'X_22', 'X_19', 'X_49', 'X_51', 'X_05', 'X_13', 'X_42', 'X_24', 'X_25', 'X_52', 'X_06', 'X_40', 'X_46', 'X_45', 'X_56', 'X_04', 'X_23', 'X_47', 'X_32', 'X_03', 'X_27', 'X_33', 'X_01', 'X_20', 'X_21', 'X_12', 'X_10', 'X_39', 'X_28', 'X_16', 'X_41']]
PR.fit(X_quad,target_y.values)
arr = PR.predict(quadratic.fit_transform(test_x.values))
preds.append(arr)
preds

[array([1.40661554, 1.50023744, 1.35408539, ..., 1.26543326, 1.17566537,
        1.32055691]),
 array([1.17405263, 1.22583945, 1.19551093, ..., 0.96757852, 0.88475016,
        0.98504364]),
 array([1.18262813, 1.14593754, 1.05064806, ..., 1.00162311, 0.95123725,
        1.03694612])]

## Y4

In [169]:
selected_x = train_df[['X_48', 'X_04', 'X_23', 'X_47', 'X_30', 'X_21', 'X_32', 'X_16', 'X_17', 'X_12', 'X_19', 'X_03', 'X_24', 'X_54', 'X_50', 'X_52', 'X_56', 'X_22', 'X_09', 'X_25', 'X_06', 'X_40', 'X_44', 'X_42', 'X_51', 'X_55', 'X_18', 'X_20', 'X_08', 'X_26', 'X_10', 'X_53', 'X_37', 'X_35', 'X_15']] # selected input : X feature
target_y = train_df['Y_04']
X_quad = quadratic.fit_transform(selected_x.values)

In [170]:
test_x = pd.read_csv('./test.csv')[['X_48', 'X_04', 'X_23', 'X_47', 'X_30', 'X_21', 'X_32', 'X_16', 'X_17', 'X_12', 'X_19', 'X_03', 'X_24', 'X_54', 'X_50', 'X_52', 'X_56', 'X_22', 'X_09', 'X_25', 'X_06', 'X_40', 'X_44', 'X_42', 'X_51', 'X_55', 'X_18', 'X_20', 'X_08', 'X_26', 'X_10', 'X_53', 'X_37', 'X_35', 'X_15']]
PR.fit(X_quad,target_y.values)
arr = PR.predict(quadratic.fit_transform(test_x.values))
preds.append(arr)
preds

[array([1.40661554, 1.50023744, 1.35408539, ..., 1.26543326, 1.17566537,
        1.32055691]),
 array([1.17405263, 1.22583945, 1.19551093, ..., 0.96757852, 0.88475016,
        0.98504364]),
 array([1.18262813, 1.14593754, 1.05064806, ..., 1.00162311, 0.95123725,
        1.03694612]),
 array([13.22508986, 13.10899956, 14.5692201 , ..., 13.88338751,
        13.39842007, 12.95210017])]

## Y5

In [171]:
selected_x = train_df[['X_48', 'X_56', 'X_32', 'X_12', 'X_15', 'X_18', 'X_17', 'X_04', 'X_23', 'X_47', 'X_33', 'X_29', 'X_09', 'X_40', 'X_54', 'X_50', 'X_44', 'X_49', 'X_51', 'X_55', 'X_03', 'X_30', 'X_19', 'X_28', 'X_53', 'X_13', 'X_35', 'X_01', 'X_06', 'X_52', 'X_37', 'X_31', 'X_45', 'X_26', 'X_10']] # selected input : X feature
target_y = train_df['Y_05']
X_quad = quadratic.fit_transform(selected_x.values)

In [172]:
test_x = pd.read_csv('./test.csv')[['X_48', 'X_56', 'X_32', 'X_12', 'X_15', 'X_18', 'X_17', 'X_04', 'X_23', 'X_47', 'X_33', 'X_29', 'X_09', 'X_40', 'X_54', 'X_50', 'X_44', 'X_49', 'X_51', 'X_55', 'X_03', 'X_30', 'X_19', 'X_28', 'X_53', 'X_13', 'X_35', 'X_01', 'X_06', 'X_52', 'X_37', 'X_31', 'X_45', 'X_26', 'X_10']]
PR.fit(X_quad,target_y.values)
arr = PR.predict(quadratic.fit_transform(test_x.values))
preds.append(arr)
preds

[array([1.40661554, 1.50023744, 1.35408539, ..., 1.26543326, 1.17566537,
        1.32055691]),
 array([1.17405263, 1.22583945, 1.19551093, ..., 0.96757852, 0.88475016,
        0.98504364]),
 array([1.18262813, 1.14593754, 1.05064806, ..., 1.00162311, 0.95123725,
        1.03694612]),
 array([13.22508986, 13.10899956, 14.5692201 , ..., 13.88338751,
        13.39842007, 12.95210017]),
 array([31.07228282, 30.94047105, 31.14679382, ..., 31.17163696,
        31.44131116, 31.08401761])]

## Y6

In [173]:
selected_x = train_df[['X_48', 'X_19', 'X_30', 'X_56', 'X_05', 'X_06', 'X_26', 'X_49', 'X_17', 'X_18', 'X_16', 'X_44', 'X_13', 'X_43', 'X_51', 'X_55', 'X_50', 'X_09', 'X_04', 'X_23', 'X_47', 'X_03', 'X_22']] # selected input : X feature
target_y = train_df['Y_06']
X_quad = quadratic.fit_transform(selected_x.values)

In [174]:
test_x = pd.read_csv('./test.csv')[['X_48', 'X_19', 'X_30', 'X_56', 'X_05', 'X_06', 'X_26', 'X_49', 'X_17', 'X_18', 'X_16', 'X_44', 'X_13', 'X_43', 'X_51', 'X_55', 'X_50', 'X_09', 'X_04', 'X_23', 'X_47', 'X_03', 'X_22']]
PR.fit(X_quad,target_y.values)
arr = PR.predict(quadratic.fit_transform(test_x.values))
preds.append(arr)
preds

[array([1.40661554, 1.50023744, 1.35408539, ..., 1.26543326, 1.17566537,
        1.32055691]),
 array([1.17405263, 1.22583945, 1.19551093, ..., 0.96757852, 0.88475016,
        0.98504364]),
 array([1.18262813, 1.14593754, 1.05064806, ..., 1.00162311, 0.95123725,
        1.03694612]),
 array([13.22508986, 13.10899956, 14.5692201 , ..., 13.88338751,
        13.39842007, 12.95210017]),
 array([31.07228282, 30.94047105, 31.14679382, ..., 31.17163696,
        31.44131116, 31.08401761]),
 array([17.02822859, 16.78892307, 16.54909589, ..., 15.83200265,
        16.21855118, 16.38044562])]

## Y7

In [175]:
selected_x = train_df[['X_48', 'X_04', 'X_23', 'X_47', 'X_19', 'X_32', 'X_21', 'X_15', 'X_18', 'X_03', 'X_17', 'X_50', 'X_54', 'X_41', 'X_24', 'X_12', 'X_14', 'X_38', 'X_31', 'X_09', 'X_56', 'X_52', 'X_06', 'X_05', 'X_22', 'X_33', 'X_29', 'X_55']] # selected input : X feature
target_y = train_df['Y_07']
X_quad = quadratic.fit_transform(selected_x.values)

In [176]:
test_x = pd.read_csv('./test.csv')[['X_48', 'X_04', 'X_23', 'X_47', 'X_19', 'X_32', 'X_21', 'X_15', 'X_18', 'X_03', 'X_17', 'X_50', 'X_54', 'X_41', 'X_24', 'X_12', 'X_14', 'X_38', 'X_31', 'X_09', 'X_56', 'X_52', 'X_06', 'X_05', 'X_22', 'X_33', 'X_29', 'X_55']]
PR.fit(X_quad,target_y.values)
arr = PR.predict(quadratic.fit_transform(test_x.values))
preds.append(arr)
preds

[array([1.40661554, 1.50023744, 1.35408539, ..., 1.26543326, 1.17566537,
        1.32055691]),
 array([1.17405263, 1.22583945, 1.19551093, ..., 0.96757852, 0.88475016,
        0.98504364]),
 array([1.18262813, 1.14593754, 1.05064806, ..., 1.00162311, 0.95123725,
        1.03694612]),
 array([13.22508986, 13.10899956, 14.5692201 , ..., 13.88338751,
        13.39842007, 12.95210017]),
 array([31.07228282, 30.94047105, 31.14679382, ..., 31.17163696,
        31.44131116, 31.08401761]),
 array([17.02822859, 16.78892307, 16.54909589, ..., 15.83200265,
        16.21855118, 16.38044562]),
 array([3.29617939, 3.19402102, 3.02348267, ..., 3.16183963, 3.16573038,
        3.22174274])]

## Y8

In [177]:
selected_x = train_df[['X_48', 'X_20', 'X_32', 'X_30', 'X_03', 'X_42', 'X_22', 'X_52', 'X_40', 'X_17', 'X_18', 'X_15', 'X_10', 'X_51', 'X_55', 'X_04', 'X_23', 'X_47', 'X_09', 'X_27', 'X_56', 'X_41', 'X_14', 'X_54', 'X_53', 'X_35', 'X_44']] # selected input : X feature
target_y = train_df['Y_08']
X_quad = quadratic.fit_transform(selected_x.values)

In [178]:
test_x = pd.read_csv('./test.csv')[['X_48', 'X_20', 'X_32', 'X_30', 'X_03', 'X_42', 'X_22', 'X_52', 'X_40', 'X_17', 'X_18', 'X_15', 'X_10', 'X_51', 'X_55', 'X_04', 'X_23', 'X_47', 'X_09', 'X_27', 'X_56', 'X_41', 'X_14', 'X_54', 'X_53', 'X_35', 'X_44']]
PR.fit(X_quad,target_y.values)
arr = PR.predict(quadratic.fit_transform(test_x.values))
preds.append(arr)
preds

[array([1.40661554, 1.50023744, 1.35408539, ..., 1.26543326, 1.17566537,
        1.32055691]),
 array([1.17405263, 1.22583945, 1.19551093, ..., 0.96757852, 0.88475016,
        0.98504364]),
 array([1.18262813, 1.14593754, 1.05064806, ..., 1.00162311, 0.95123725,
        1.03694612]),
 array([13.22508986, 13.10899956, 14.5692201 , ..., 13.88338751,
        13.39842007, 12.95210017]),
 array([31.07228282, 30.94047105, 31.14679382, ..., 31.17163696,
        31.44131116, 31.08401761]),
 array([17.02822859, 16.78892307, 16.54909589, ..., 15.83200265,
        16.21855118, 16.38044562]),
 array([3.29617939, 3.19402102, 3.02348267, ..., 3.16183963, 3.16573038,
        3.22174274]),
 array([-26.17950333, -26.09642685, -25.6653241 , ..., -26.62554062,
        -26.59866036, -26.63975037])]

## Y9

In [179]:
selected_x = train_df[['X_48', 'X_20', 'X_30', 'X_42', 'X_03', 'X_32', 'X_22', 'X_52', 'X_40', 'X_17', 'X_18', 'X_15', 'X_04', 'X_23', 'X_47', 'X_51', 'X_55', 'X_09', 'X_12', 'X_41', 'X_10', 'X_14', 'X_56', 'X_54', 'X_53', 'X_35']] # selected input : X feature
target_y = train_df['Y_09']
X_quad = quadratic.fit_transform(selected_x.values)

In [180]:
test_x = pd.read_csv('./test.csv')[['X_48', 'X_20', 'X_30', 'X_42', 'X_03', 'X_32', 'X_22', 'X_52', 'X_40', 'X_17', 'X_18', 'X_15', 'X_04', 'X_23', 'X_47', 'X_51', 'X_55', 'X_09', 'X_12', 'X_41', 'X_10', 'X_14', 'X_56', 'X_54', 'X_53', 'X_35']]
PR.fit(X_quad,target_y.values)
arr = PR.predict(quadratic.fit_transform(test_x.values))
preds.append(arr)
preds

[array([1.40661554, 1.50023744, 1.35408539, ..., 1.26543326, 1.17566537,
        1.32055691]),
 array([1.17405263, 1.22583945, 1.19551093, ..., 0.96757852, 0.88475016,
        0.98504364]),
 array([1.18262813, 1.14593754, 1.05064806, ..., 1.00162311, 0.95123725,
        1.03694612]),
 array([13.22508986, 13.10899956, 14.5692201 , ..., 13.88338751,
        13.39842007, 12.95210017]),
 array([31.07228282, 30.94047105, 31.14679382, ..., 31.17163696,
        31.44131116, 31.08401761]),
 array([17.02822859, 16.78892307, 16.54909589, ..., 15.83200265,
        16.21855118, 16.38044562]),
 array([3.29617939, 3.19402102, 3.02348267, ..., 3.16183963, 3.16573038,
        3.22174274]),
 array([-26.17950333, -26.09642685, -25.6653241 , ..., -26.62554062,
        -26.59866036, -26.63975037]),
 array([-26.19552678, -26.13064331, -25.69644207, ..., -26.59562129,
        -26.58581084, -26.59303469])]

## Y10

In [181]:
selected_x = train_df[['X_48', 'X_04', 'X_23', 'X_47', 'X_18', 'X_15', 'X_22', 'X_42', 'X_30', 'X_56', 'X_49', 'X_03', 'X_09', 'X_51', 'X_16', 'X_27', 'X_24', 'X_41', 'X_32', 'X_45', 'X_17', 'X_21', 'X_01', 'X_40', 'X_55', 'X_52', 'X_54', 'X_53', 'X_29', 'X_10', 'X_08', 'X_44', 'X_31', 'X_50', 'X_07']] # selected input : X feature
target_y = train_df['Y_10']
X_quad = quadratic.fit_transform(selected_x.values)

In [182]:
test_x = pd.read_csv('./test.csv')[['X_48', 'X_04', 'X_23', 'X_47', 'X_18', 'X_15', 'X_22', 'X_42', 'X_30', 'X_56', 'X_49', 'X_03', 'X_09', 'X_51', 'X_16', 'X_27', 'X_24', 'X_41', 'X_32', 'X_45', 'X_17', 'X_21', 'X_01', 'X_40', 'X_55', 'X_52', 'X_54', 'X_53', 'X_29', 'X_10', 'X_08', 'X_44', 'X_31', 'X_50', 'X_07']]
PR.fit(X_quad,target_y.values)
arr = PR.predict(quadratic.fit_transform(test_x.values))
preds.append(arr)
preds

[array([1.40661554, 1.50023744, 1.35408539, ..., 1.26543326, 1.17566537,
        1.32055691]),
 array([1.17405263, 1.22583945, 1.19551093, ..., 0.96757852, 0.88475016,
        0.98504364]),
 array([1.18262813, 1.14593754, 1.05064806, ..., 1.00162311, 0.95123725,
        1.03694612]),
 array([13.22508986, 13.10899956, 14.5692201 , ..., 13.88338751,
        13.39842007, 12.95210017]),
 array([31.07228282, 30.94047105, 31.14679382, ..., 31.17163696,
        31.44131116, 31.08401761]),
 array([17.02822859, 16.78892307, 16.54909589, ..., 15.83200265,
        16.21855118, 16.38044562]),
 array([3.29617939, 3.19402102, 3.02348267, ..., 3.16183963, 3.16573038,
        3.22174274]),
 array([-26.17950333, -26.09642685, -25.6653241 , ..., -26.62554062,
        -26.59866036, -26.63975037]),
 array([-26.19552678, -26.13064331, -25.69644207, ..., -26.59562129,
        -26.58581084, -26.59303469]),
 array([-22.34997098, -22.16896883, -21.95401703, ..., -22.63747582,
        -22.49835   , -22.66555667

## Y11

In [183]:
selected_x = train_df[['X_48', 'X_17', 'X_18', 'X_15', 'X_30', 'X_51', 'X_42', 'X_03', 'X_01', 'X_56', 'X_05', 'X_54', 'X_31', 'X_21', 'X_52', 'X_55', 'X_10', 'X_50', 'X_04', 'X_23', 'X_47', 'X_32', 'X_09', 'X_33', 'X_35']] # selected input : X feature
target_y = train_df['Y_11']
X_quad = quadratic.fit_transform(selected_x.values)

In [184]:
test_x = pd.read_csv('./test.csv')[['X_48', 'X_17', 'X_18', 'X_15', 'X_30', 'X_51', 'X_42', 'X_03', 'X_01', 'X_56', 'X_05', 'X_54', 'X_31', 'X_21', 'X_52', 'X_55', 'X_10', 'X_50', 'X_04', 'X_23', 'X_47', 'X_32', 'X_09', 'X_33', 'X_35']]
PR.fit(X_quad,target_y.values)
arr = PR.predict(quadratic.fit_transform(test_x.values))
preds.append(arr)
preds

[array([1.40661554, 1.50023744, 1.35408539, ..., 1.26543326, 1.17566537,
        1.32055691]),
 array([1.17405263, 1.22583945, 1.19551093, ..., 0.96757852, 0.88475016,
        0.98504364]),
 array([1.18262813, 1.14593754, 1.05064806, ..., 1.00162311, 0.95123725,
        1.03694612]),
 array([13.22508986, 13.10899956, 14.5692201 , ..., 13.88338751,
        13.39842007, 12.95210017]),
 array([31.07228282, 30.94047105, 31.14679382, ..., 31.17163696,
        31.44131116, 31.08401761]),
 array([17.02822859, 16.78892307, 16.54909589, ..., 15.83200265,
        16.21855118, 16.38044562]),
 array([3.29617939, 3.19402102, 3.02348267, ..., 3.16183963, 3.16573038,
        3.22174274]),
 array([-26.17950333, -26.09642685, -25.6653241 , ..., -26.62554062,
        -26.59866036, -26.63975037]),
 array([-26.19552678, -26.13064331, -25.69644207, ..., -26.59562129,
        -26.58581084, -26.59303469]),
 array([-22.34997098, -22.16896883, -21.95401703, ..., -22.63747582,
        -22.49835   , -22.66555667

## Y12

In [185]:
selected_x = train_df[['X_48', 'X_20', 'X_30', 'X_42', 'X_03', 'X_32', 'X_22', 'X_56', 'X_40', 'X_18', 'X_15', 'X_51', 'X_04', 'X_23', 'X_47', 'X_09', 'X_13', 'X_10', 'X_41', 'X_55', 'X_52', 'X_12', 'X_54', 'X_53', 'X_35']] # selected input : X feature
target_y = train_df['Y_12']
X_quad = quadratic.fit_transform(selected_x.values)

In [186]:
test_x = pd.read_csv('./test.csv')[['X_48', 'X_20', 'X_30', 'X_42', 'X_03', 'X_32', 'X_22', 'X_56', 'X_40', 'X_18', 'X_15', 'X_51', 'X_04', 'X_23', 'X_47', 'X_09', 'X_13', 'X_10', 'X_41', 'X_55', 'X_52', 'X_12', 'X_54', 'X_53', 'X_35']]
PR.fit(X_quad,target_y.values)
arr = PR.predict(quadratic.fit_transform(test_x.values))
preds.append(arr)
preds

[array([1.40661554, 1.50023744, 1.35408539, ..., 1.26543326, 1.17566537,
        1.32055691]),
 array([1.17405263, 1.22583945, 1.19551093, ..., 0.96757852, 0.88475016,
        0.98504364]),
 array([1.18262813, 1.14593754, 1.05064806, ..., 1.00162311, 0.95123725,
        1.03694612]),
 array([13.22508986, 13.10899956, 14.5692201 , ..., 13.88338751,
        13.39842007, 12.95210017]),
 array([31.07228282, 30.94047105, 31.14679382, ..., 31.17163696,
        31.44131116, 31.08401761]),
 array([17.02822859, 16.78892307, 16.54909589, ..., 15.83200265,
        16.21855118, 16.38044562]),
 array([3.29617939, 3.19402102, 3.02348267, ..., 3.16183963, 3.16573038,
        3.22174274]),
 array([-26.17950333, -26.09642685, -25.6653241 , ..., -26.62554062,
        -26.59866036, -26.63975037]),
 array([-26.19552678, -26.13064331, -25.69644207, ..., -26.59562129,
        -26.58581084, -26.59303469]),
 array([-22.34997098, -22.16896883, -21.95401703, ..., -22.63747582,
        -22.49835   , -22.66555667

## Y13

In [187]:
selected_x = train_df[['X_48', 'X_20', 'X_30', 'X_42', 'X_03', 'X_32', 'X_22', 'X_52', 'X_40', 'X_17', 'X_18', 'X_15', 'X_51', 'X_04', 'X_23', 'X_47', 'X_09', 'X_55', 'X_10', 'X_56', 'X_41', 'X_14', 'X_12', 'X_54', 'X_53', 'X_35']] # selected input : X feature
target_y = train_df['Y_13']
X_quad = quadratic.fit_transform(selected_x.values)

In [188]:
test_x = pd.read_csv('./test.csv')[['X_48', 'X_20', 'X_30', 'X_42', 'X_03', 'X_32', 'X_22', 'X_52', 'X_40', 'X_17', 'X_18', 'X_15', 'X_51', 'X_04', 'X_23', 'X_47', 'X_09', 'X_55', 'X_10', 'X_56', 'X_41', 'X_14', 'X_12', 'X_54', 'X_53', 'X_35']]
PR.fit(X_quad,target_y.values)
arr = PR.predict(quadratic.fit_transform(test_x.values))
preds.append(arr)
preds

[array([1.40661554, 1.50023744, 1.35408539, ..., 1.26543326, 1.17566537,
        1.32055691]),
 array([1.17405263, 1.22583945, 1.19551093, ..., 0.96757852, 0.88475016,
        0.98504364]),
 array([1.18262813, 1.14593754, 1.05064806, ..., 1.00162311, 0.95123725,
        1.03694612]),
 array([13.22508986, 13.10899956, 14.5692201 , ..., 13.88338751,
        13.39842007, 12.95210017]),
 array([31.07228282, 30.94047105, 31.14679382, ..., 31.17163696,
        31.44131116, 31.08401761]),
 array([17.02822859, 16.78892307, 16.54909589, ..., 15.83200265,
        16.21855118, 16.38044562]),
 array([3.29617939, 3.19402102, 3.02348267, ..., 3.16183963, 3.16573038,
        3.22174274]),
 array([-26.17950333, -26.09642685, -25.6653241 , ..., -26.62554062,
        -26.59866036, -26.63975037]),
 array([-26.19552678, -26.13064331, -25.69644207, ..., -26.59562129,
        -26.58581084, -26.59303469]),
 array([-22.34997098, -22.16896883, -21.95401703, ..., -22.63747582,
        -22.49835   , -22.66555667

## Y14

In [189]:
selected_x = train_df[['X_48', 'X_20', 'X_32', 'X_30', 'X_03', 'X_42', 'X_22', 'X_52', 'X_40', 'X_18', 'X_15', 'X_04', 'X_23', 'X_47', 'X_51', 'X_55', 'X_09', 'X_27', 'X_10', 'X_56', 'X_54', 'X_41', 'X_13', 'X_53', 'X_12', 'X_35']] # selected input : X feature
target_y = train_df['Y_14']
X_quad = quadratic.fit_transform(selected_x.values)

In [190]:
test_x = pd.read_csv('./test.csv')[['X_48', 'X_20', 'X_32', 'X_30', 'X_03', 'X_42', 'X_22', 'X_52', 'X_40', 'X_18', 'X_15', 'X_04', 'X_23', 'X_47', 'X_51', 'X_55', 'X_09', 'X_27', 'X_10', 'X_56', 'X_54', 'X_41', 'X_13', 'X_53', 'X_12', 'X_35']]
PR.fit(X_quad,target_y.values)
arr = PR.predict(quadratic.fit_transform(test_x.values))
preds.append(arr)
preds

[array([1.40661554, 1.50023744, 1.35408539, ..., 1.26543326, 1.17566537,
        1.32055691]),
 array([1.17405263, 1.22583945, 1.19551093, ..., 0.96757852, 0.88475016,
        0.98504364]),
 array([1.18262813, 1.14593754, 1.05064806, ..., 1.00162311, 0.95123725,
        1.03694612]),
 array([13.22508986, 13.10899956, 14.5692201 , ..., 13.88338751,
        13.39842007, 12.95210017]),
 array([31.07228282, 30.94047105, 31.14679382, ..., 31.17163696,
        31.44131116, 31.08401761]),
 array([17.02822859, 16.78892307, 16.54909589, ..., 15.83200265,
        16.21855118, 16.38044562]),
 array([3.29617939, 3.19402102, 3.02348267, ..., 3.16183963, 3.16573038,
        3.22174274]),
 array([-26.17950333, -26.09642685, -25.6653241 , ..., -26.62554062,
        -26.59866036, -26.63975037]),
 array([-26.19552678, -26.13064331, -25.69644207, ..., -26.59562129,
        -26.58581084, -26.59303469]),
 array([-22.34997098, -22.16896883, -21.95401703, ..., -22.63747582,
        -22.49835   , -22.66555667

# Evaluation

In [191]:
#LR.score(train_x, train_y) # train set
#LR.score(test_x, preds) # 

39608

# Submit

In [195]:
submit = pd.read_csv('./sample_submission.csv')

In [196]:
for idx, col in enumerate(submit.columns):
    if col=='ID':
        continue
    submit[col] = preds[:][idx-1]
print('Done.')

Done.


In [197]:
submit.to_csv('./submit_PR_selected.csv', index=False)